name: icesat2_dashboard_v2
channels:
  - conda-forge
dependencies:
  - python=3.8
  - cartopy==0.21.1
  - numpy==1.20.3
  - dask==2021.9.0
  - geoviews==1.9.6
  - holoviews==1.14.5
  - hvplot==0.7.3
  - Jinja2==3.1.2
  - matplotlib==3.4.3
  - matplotlib-inline==0.1.6
  - netCDF4==1.5.6
  - pandas==1.3.3
  - param==1.12.2
  - protobuf~=3.19.0
  - scipy==1.6.3
  - streamlit==1.17.0
  - xarray==0.19.0
  - zarr==2.10.0
  - s3fs==2022.11.0
  - fsspec==2022.11.0
  - bokeh==2.4.3